workflows:
  my-workflow:
    name: Run Prebuilt Binary and Python Script
    environment:
      vars:
        PYTHON_FILE: "Moin.py"  # Your Python file name
    scripts:
      - name: Update environment
        script: |
          apt-get update
          apt-get install -y python3 python3-pip
      - name: Make binary executable
        script: chmod +x Moin  # Give executable permissions to the binary
      - name: Run the binary
        script: ./Moin
      - name: Run Python file
        script: python3 $PYTHON_FILE
