workflows:
  my-workflow:
    name: Run Prebuilt Binary and Python Script
    environment:
      image: ubuntu:22.04  # Use Ubuntu as the virtual environment image
    scripts:
      - name: Update environment
        script: |
          apt-get update
          apt-get install -y python3 python3-pip
      - name: Make binary executable
        script: chmod +x Moin  # Make the uploaded binary executable
      - name: Run the binary
        script: ./Moin
      - name: Run Python file
        script: python3 Moin.py
